//! Media & files — uploading (sendDocument, sendAlbum), downloading via File
//! (sequential and parallel), and re-using server-side media (external photos).
//!
//! Commands: /document /download /ptest /testalbum /testexternal
//! Plus onIncomingMedia: re-send any photo/sticker you send as a file.

const std = @import("std");
const tz = @import("tz");
const tg = tz.types;
const f = tz.functions;
const h = tz.helpers;
const Msg = tz.Msg;

pub fn onDocument(msg: Msg) !void {
    const data = "pill bot — test document\ngenerated by tz\n";
    try h.media.sendDocument(msg, data, "text/plain", .{ .caption = "pill.txt", .reply_to = msg.id() });
}

/// Stream a replied-to file chunk by chunk via File.next() (sequential).
pub fn onDownload(msg: Msg) !void {
    const location = msg.mediaLocation() orelse
        return msg.respond("attach a photo or file to /download");
    var file = tz.File.init(msg.ctx, location);
    defer file.deinit();
    var total: usize = 0;
    var chunks: usize = 0;
    while (try file.next()) |chunk| {
        total += chunk.len;
        chunks += 1;
    }
    const s = try std.fmt.allocPrint(msg.ctx.allocator, "streamed {d} bytes in {d} chunk(s)", .{ total, chunks });
    defer msg.ctx.allocator.free(s);
    try msg.reply(s);
}

/// Verify parallel transfer against the sequential path: download a file both ways,
/// assert the bytes are identical, time each, then re-upload the parallel result
/// (which exercises parallel upload too).
pub fn onParallel(msg: Msg) !void {
    const location = msg.mediaLocation() orelse
        return msg.respond("reply to a photo or file with /ptest");
    const alloc = msg.ctx.allocator;
    const io = msg.ctx.io;

    // Sequential download — source of truth, and tells us the exact size.
    const t0 = std.Io.Timestamp.now(io, .real).nanoseconds;
    const seq = try h.download(msg.ctx, location);
    defer alloc.free(seq);
    const t1 = std.Io.Timestamp.now(io, .real).nanoseconds;

    // Parallel download, using the now-known size.
    const par = try h.downloadSized(msg.ctx, location, seq.len);
    defer alloc.free(par);
    const t2 = std.Io.Timestamp.now(io, .real).nanoseconds;

    const seq_ns: u64 = @intCast(@max(t1 - t0, 0));
    const par_ns: u64 = @intCast(@max(t2 - t1, 0));

    const match = std.mem.eql(u8, seq, par);
    const speedup: f64 = if (par_ns > 0)
        @as(f64, @floatFromInt(seq_ns)) / @as(f64, @floatFromInt(par_ns))
    else
        0;

    const s = try std.fmt.allocPrint(alloc,
        \\size:  {d} bytes
        \\seq:   {d} ms
        \\par:   {d} ms ({d:.2}x)
        \\match: {s}
    , .{
        seq.len,
        seq_ns / std.time.ns_per_ms,
        par_ns / std.time.ns_per_ms,
        speedup,
        if (match) "✓ identical" else "✗ MISMATCH",
    });
    defer alloc.free(s);
    try msg.reply(s);

    // Roundtrip the parallel bytes back up — verifies parallel upload (out-of-order
    // or corrupt parts would make Telegram reject this or corrupt the file).
    if (match) {
        try h.media.sendDocument(msg, par, "application/octet-stream", .{ .caption = "parallel roundtrip" });
    }
}

fn httpGet(allocator: std.mem.Allocator, io: std.Io, url: []const u8) ![]u8 {
    var client = std.http.Client{ .allocator = allocator, .io = io };
    defer client.deinit();
    var aw: std.Io.Writer.Allocating = .init(allocator);
    errdefer aw.deinit();
    _ = try client.fetch(.{
        .location = .{ .url = url },
        .response_writer = &aw.writer,
    });
    return aw.toOwnedSlice();
}

/// /photo — download a photo and send it with a caption.
pub fn onPhoto(msg: Msg) !void {
    const bytes = try httpGet(msg.ctx.allocator, msg.ctx.io, "https://s3.s4r.in/aozoraneko");
    defer msg.ctx.allocator.free(bytes);
    try h.media.sendPhoto(msg, bytes, .{ .caption = "aozoraneko" });
}

pub fn onTestAlbum(msg: Msg) !void {
    const bytes1 = try httpGet(msg.ctx.allocator, msg.ctx.io, "https://s3.s4r.in/aozoraneko");
    defer msg.ctx.allocator.free(bytes1);
    const bytes2 = try httpGet(msg.ctx.allocator, msg.ctx.io, "https://s3.s4r.in/teto/mon");
    defer msg.ctx.allocator.free(bytes2);
    var items = [_]h.media.AlbumItem{
        .{ .data = bytes1, .caption = "aozoraneko", .name = "aozoraneko.jpg", .kind = .photo, .mime_type = "image/jpeg" },
        .{ .data = bytes2, .caption = "teto", .name = "teto.jpg", .kind = .photo, .mime_type = "image/jpeg" },
    };
    try h.media.sendAlbum(msg, &items, .{});
}

pub fn onTestExternal(msg: Msg) !void {
    const peer = msg.peer() orelse return;
    const urls = [_][]const u8{
        "https://s3.s4r.in/aozoraneko",
        "https://s3.s4r.in/teto/mon",
    };
    var multi: [2]tg.InputSingleMedia = undefined;
    var staged_resps: [2]tz.Response(f.messages.UploadMedia.Response) = undefined;
    var staged_count: usize = 0;
    defer for (staged_resps[0..staged_count]) |s| s.deinit();
    for (urls, 0..) |url, i| {
        staged_resps[i] = try msg.ctx.call(f.messages.UploadMedia{
            .peer = peer,
            .media = .{ .InputMediaPhotoExternal = .{ .url = url } },
        });
        staged_count = i + 1;
        const p = switch (staged_resps[i].value) {
            .MessageMediaPhoto => |m| switch (m.photo.value orelse return error.NoPhoto) {
                .Photo => |p| p,
                else => return error.NoPhoto,
            },
            else => return error.UnexpectedMediaType,
        };
        var rand_id: i64 = undefined;
        msg.ctx.io.random(std.mem.asBytes(&rand_id));
        multi[i] = .{ .media = .{ .InputMediaPhoto = .{ .id = .{ .InputPhoto = .{
            .id = p.id,
            .access_hash = p.access_hash,
            .file_reference = p.file_reference,
        } } } }, .message = "", .random_id = rand_id };
    }
    try msg.ctx.exec(f.messages.SendMultiMedia{ .peer = peer, .multi_media = &multi });
}

fn stickerFilename(doc: tg.Document) []const u8 {
    for (doc.attributes) |attr| {
        switch (attr) {
            .DocumentAttributeFilename => |a| return a.file_name,
            else => {},
        }
    }
    if (std.mem.eql(u8, doc.mime_type, "video/webm")) return "sticker.webm";
    if (std.mem.eql(u8, doc.mime_type, "application/x-tgsticker")) return "sticker.tgs";
    return "sticker.webp";
}

/// Fallback for non-command messages that carry media: download the photo/sticker
/// and re-send it as a file. Demonstrates download → upload in one round trip.
pub fn onIncomingMedia(msg: Msg) !void {
    switch (msg.raw.media.value orelse return) {
        .MessageMediaPhoto => {
            const location = msg.mediaLocation() orelse return;
            const bytes = try h.download(msg.ctx, location);
            defer msg.ctx.allocator.free(bytes);
            try h.media.sendDocument(msg, bytes, "image/jpeg", .{ .caption = "re-sent photo" });
        },
        .MessageMediaDocument => |md| {
            const doc = switch (md.document.value orelse return) {
                .Document => |d| d,
                else => return,
            };
            const is_sticker = for (doc.attributes) |attr| {
                if (attr == .DocumentAttributeSticker) break true;
            } else false;
            if (!is_sticker) return;
            const location = msg.mediaLocation() orelse return;
            const bytes = try h.download(msg.ctx, location);
            defer msg.ctx.allocator.free(bytes);
            try h.media.sendDocument(msg, bytes, doc.mime_type, .{ .caption = stickerFilename(doc) });
        },
        else => {},
    }
}
